travis:
  secure:
    BINSTAR_TOKEN: ps6HYpLRn0/5nlfAV6ZlTiECi69Jj10u8OfS8EOgMpFWvdmlBjGxbKklvT3VOFFeqLn65kLYIvjmfZNsm7Ruoz4+oiXXiAKbkCZFcrabFXle3N4CRipYACPwZkU9tdYxSIV6RYEZLHfSIArqyZfT2HmyktaS+TQrd6GMyQgv6hNoVoFno1KiyYq7gHr9fqPMHPz80p1/CegWZnuF8UafgjZLzzVHJ/KvYs1XexFOWh8JAzD4Hc6HULEvTGfjVJowlke4viganYyyMeGlCOeHb/2Lsn81/F9v0jaSBrupDKaTg1QePDloqzqjpDiYxbljSuJxPQ6jzdz/IkWUGxjszLypca414JA58C1yYxPArtLmob/OX0i7fK5XDr4QDHla0Z+2XJQbm/2anmb7lPoSabpmZsQw6q4KU7Ex1P068rFfsG7yD264cAcFlfqEk1/h7vsfFjtj/h2B37frakbxD2P6UKbztNBGyi3fyicol5P6bMV3+ss8tZIztHP5EWtzGB4WT6+DfEWS81+t9ciHSk77UBnbyyNvmls8ZYSReBEm1RfzJhxTdNvNHipy51ZkEtzxbJMzJuCfoMyJRBPbf0olYcOfb1dQkmFx91h52/hdNeubCh9+td85CVrc/3rvSSh5aFClf43iBlQWGvKlV/TmXdnmE8XfwSdR36eDgE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
